Repository marcboeker/go-duckdb, pull requests merged in 2024-06, with the labels that each got.

#205 Use build tags for Arrow implementation
  README.md
  arrow.go
  arrow_test.go
Labels: ready to merge, build

#208 Replacement scan
  replacement_scan.go
  replacement_scan_test.go
Labels: feature, ready to merge

#233 Initial DataChunk API support
  appender.go
  data_chunk.go
  errors.go
  errors_test.go
  helper.go
  statement.go
  vector.go
  vector_setters.go
Labels: enhancement, feature, ready to merge

#237 Appender support for TIME, INTERVAL, HUGEINT, DECIMAL, ENUM, and MAP
  appender.go
  appender_test.go
  data_chunk.go
  errors.go
  errors_test.go
  rows.go
  types.go
  types_test.go
  vector.go
  vector_setters.go
Labels: feature

#240 Move row scanning int the data chunk interface
  data_chunk.go
  rows.go
  vector.go
  vector_getters.go
Labels: enhancement
