Repository marcboeker/go-duckdb, pull requests merged in 2024-09, with the labels that each got.

#272 [Feature] Type interface
  appender.go
  connection.go
  data_chunk.go
  duckdb.go
  duckdb_test.go
  errors.go
  errors_test.go
  replacement_scan.go
  rows.go
  statement.go
  type.go
  type_info.go
  type_info_test.go
  types.go
  vector.go
  vector_getters.go
  vector_setters.go
Labels: feature

#276 Add generic setters to void casting values to any
  appender_test.go
  data_chunk.go
  errors_test.go
  type_info.go
  types_test.go
  vector.go
  vector_getters.go
  vector_setters.go
Labels: enhancement

#222 [Feature] Scalar UDF support
  Makefile
  data_chunk.go
  errors.go
  examples/scalar_udf/main.go
  scalar_udf.go
  scalar_udf_test.go
  type_info.go
  type_info_test.go
  types.go
  udf_utils.go
  vector.go
  vector_getters.go
  vector_setters.go
Labels: feature

#285 Update the profiling example in the README
  README.md
Labels: documentation
