Repository marcboeker/go-duckdb, pull requests merged in 2024-10, with the labels that each got.

#287 [Documentation] Add note about undefined conn
  README.md
Labels: documentation

#247 docs: Support godoc examples for 'simple' and 'advanced' configurations, add GoDoc badge
  .gitignore
  duckdb_test.go
  errors.go
  type_info.go
  types.go
  vector_setters.go
Labels: documentation

#288 Add godoc badge
  README.md
Labels: documentation

#201 Table function UDFs
  Makefile
  errors.go
  examples/table_udf/main.go
  examples/table_udf_parallel/main.go
  replacement_scan.go
  row.go
  scalarUDF.go
  scalarUDF_test.go
  tableUDF.go
  tableUDF_test.go
  udf_utils.go
  value.go
  vector_getters.go
Labels: feature

#293 Add steps for windows build
  Makefile
  README.md
  cgo_static.go
Labels: [OS] Windows, documentation

#294 Add support for renaming struct fields
  appender_test.go
  errors_test.go
  vector_setters.go
Labels: feature

#295 Fix comparison against nil for the UUID type
  appender_test.go
  vector.go
Labels: changes requested, fix

#298 Update to Go 1.23
  go.mod
Labels: go

#300 PrepareContext support
  connection.go
  duckdb.go
  duckdb_test.go
  errors.go
  errors_test.go
  statement_test.go
Labels: feature, fix
