Repository marcboeker/go-duckdb, pull requests merged in 2025-06, with the labels that each got.

#455 Use runtime reflection type to bind query parameters
  connection.go
  statement.go
  statement_test.go
  value.go
Labels: feature / enhancement, changes requested

#472 [Nit] Better error message
  errors.go
Labels: feature / enhancement

#471 [Fix] Follow-up to fix time zone issues
  connection.go
  duckdb.go
  scalar_udf_test.go
  statement.go
  statement_test.go
  table_udf_test.go
  type_info_test.go
  types.go
  types_test.go
Labels: fix

#473 Update mappings to latest duckdb-go-bindings
  arrowmapping/go.mod
  arrowmapping/go.sum
  mapping/go.mod
  mapping/go.sum
Labels: dependencies

#474 Update to duckdb 1.3.1
  .github/workflows/tests.yaml
  README.md
  go.mod
  go.sum
Labels: dependencies
