Repository marcboeker/go-duckdb, pull requests merged in 2025-02, with the labels that each got.

#358 Update dependencies
  appender_test.go
  go.mod
  go.sum
  types.go
Labels: dependencies

#361 feature: allow :memory: in DSN
  duckdb.go
  duckdb_test.go
Labels: feature / enhancement

#372 Add test wrappers PR 2 - arrow_test and duckdb_extensions_test
  arrow_test.go
  duckdb_extensions_test.go
  duckdb_test.go
Labels: testing

#373 Add test wrappers PR 3 - appender_test and errors_test
  appender_test.go
  duckdb_test.go
  errors_test.go
  types_test.go
Labels: testing

#374 Add test wrappers PR 4 - profiling_test, replacement_scan_test, and scalarUDF_test
  profiling_test.go
  replacement_scan_test.go
  scalarUDF_test.go
Labels: testing

#376 Add test wrappers PR 5 - tableUDF_test, type_info_test, and types_test
  duckdb_test.go
  tableUDF_test.go
  type_info_test.go
  types_test.go
Labels: testing

#379 Update to Go 1.24
  .github/workflows/golangci-lint.yml
  .github/workflows/tests.yaml
  go.mod
  go.sum
Labels: dependencies, go, CI / infra

#378 Add mapping module and arrow-mapping module
  arrowmapping/arrow_mapping.go
  arrowmapping/arrow_mapping_darwin_amd64.go
  arrowmapping/arrow_mapping_darwin_arm64.go
  arrowmapping/arrow_mapping_linux_amd64.go
  arrowmapping/arrow_mapping_linux_arm64.go
  arrowmapping/arrow_mapping_windows_amd64.go
  arrowmapping/go.mod
  arrowmapping/go.sum
  mapping/go.mod
  mapping/go.sum
  mapping/mapping.go
  mapping/mapping_darwin_amd64.go
  mapping/mapping_darwin_arm64.go
  mapping/mapping_linux_amd64.go
  mapping/mapping_linux_arm64.go
  mapping/mapping_windows_amd64.go
Labels: feature / enhancement, go
