Repository marcboeker/go-duckdb, pull requests merged in 2025-05, with the labels that each got.

#435 Add support for timestamp_s, timestamp_ms and timestamp_ns
  statement.go
  statement_test.go
  table_udf_test.go
  types.go
  value.go
  vector_getters.go
  vector_setters.go
Labels: feature / enhancement, changes requested

#438 [Fix] Mismatch local state type for parallel chunk table UDFs
  table_udf.go
  table_udf_test.go
Labels: fix

#441 [Fix] Some binding cases of JSON parameters
  statement.go
  statement_test.go
Labels: fix

#447 Update mappings to DuckDB 1.3.0
  arrowmapping/go.mod
  arrowmapping/go.sum
  mapping/go.mod
  mapping/go.sum
Labels: dependencies

#449 Update duckdb version to 1.3.0
  .github/workflows/tests.yaml
  Makefile
  README.md
  go.mod
  go.sum
Labels: dependencies
