Repository marcboeker/go-duckdb, pull requests merged in 2025-09, with the labels that each got.

#523 fix: Handle crash in replacement table scan
  replacement_scan.go
Labels: fix

#538 Update mappings
  arrowmapping/go.mod
  arrowmapping/go.sum
  mapping/go.mod
  mapping/go.sum
Labels: dependencies

#541 Update to DuckDB 1.4
  .github/workflows/tests.yaml
  README.md
  connection_test.go
  duckdb_test.go
  go.mod
  go.sum
  type.go
Labels: dependencies

#544 Update mappings
  .github/workflows/tests.yaml
  go.mod
  go.sum
Labels: dependencies

#547 Test empty profiling info
  profiling_test.go
Labels: testing

#551 Use error data and some appender cleanup
  appender.go
  errors.go
Labels: feature / enhancement

#554 Update `README.md` with connection pooling note
  README.md
Labels: documentation

#545 Implement NewQueryAppender
  appender.go
  appender_test.go
  duckdb_test.go
  errors.go
  errors_test.go
  type_info.go
  value.go
Labels: feature / enhancement
