Repository marcboeker/go-duckdb, pull requests merged in 2025-04, with the labels that each got.

#408 [Documentation] Expand breaking changes section and add JSON scanning notice
  README.md
Labels: question / help wanted, documentation

#412 Move mapping and arrowmapping to duckdb 1.2.2
  arrowmapping/go.mod
  arrowmapping/go.sum
  mapping/go.mod
  mapping/go.sum
  mapping/mapping.go
  mapping/mapping_darwin_amd64.go
  mapping/mapping_darwin_arm64.go
  mapping/mapping_linux_amd64.go
  mapping/mapping_linux_arm64.go
  mapping/mapping_windows_amd64.go
Labels: dependencies

#413 Update mapping and arrow mapping module version in main go mod
  go.mod
  go.sum
Labels: dependencies

#416 Do not use the instance cache for in-memory databases
  duckdb.go
  duckdb_test.go
Labels: fix

#415 Handle JSON type in DatabaseTypeName and ScanType
  rows.go
  types_test.go
Labels: fix

#356 Add support for UNION types
  appender_test.go
  duckdb_test.go
  rows.go
  scalar_udf_test.go
  statement.go
  table_udf_test.go
  type.go
  type_info.go
  type_info_test.go
  types.go
  types_test.go
  vector.go
  vector_getters.go
  vector_setters.go
Labels: feature / enhancement

#428 Call AppendDataChunk immediately instead of caching data chunks in the Appender
  appender.go
  appender_test.go
  errors_test.go
Labels: fix

#423 Add support for binding lists, arrays, and structs to prepared queries
  connection.go
  statement.go
  statement_test.go
  value.go
  vector.go
  vector_setters.go
Labels: feature / enhancement
